### ISSUE TITLE
Overexposure of flashlight is making image white.

### ISSUE THREAD

**Issue by abhishekbaghel05** [googlesamples/android-Camera2Basic#104]
I am capturing an Image with flashlight on. But images are coming over exposed with flash. I am using Smartron SRT phone with Android 7.1.2. How can I resolve it?

**Comment by rtr321** [comment]
Same problem

**Comment by ElteHupkes** [comment]
I'm experiencing the same issue on a Sony Xperia X Compact. The precapture code in this sample has always seemed rather strange to me. I'm gonna try to figure out what the problem is, will report back if I figure it out.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
