### ISSUE TITLE
camera quality bad

### ISSUE THREAD

**Issue by aviontechnology** [googlesamples/android-Camera2Basic#105]
thanks in advance 
as compare to google camera quality, this google sample is showing very blur camera preview.
please give some solution to show good quality camera preview as per google camera application.
captured image quality is also low and very pix lated  ,please give some solution.

thank you again

**Comment by hong82** [comment]
did u try to add an autofocus?

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
