### ISSUE TITLE
dequeueBuffer: createGraphicBuffer failed

### ISSUE THREAD

**Issue by elediam** [googlesamples/android-Camera2Basic#108]
I am using camera 2 api for repeating capture requests which is done successfully until it reaches the 465 photos taken where it freezes due to failure to dequeue the buffer. 

05-11 17:15:59.494 23926-23939/com.example.ediamanti.digitalimageprocessing E/BufferQueueProducer: [ImageReader-4048x3036f100m60-23926-469] dequeueBuffer: createGraphicBuffer failed
05-11 17:15:59.494 721-4751/? E/Camera3-OutputStream: getBufferLockedCommon: Stream 1: Can't dequeue next output buffer: Out of memory (-12)
05-11 17:15:59.494 721-4751/? E/Camera3-Device: RequestThread: Can't get output buffer, skipping request: Out of memory (-12)
05-11 17:15:59.504 676-4782/? E/mm-camera: <ISP   ><ERROR> 1255: isp_handler_module_handle_reg_update:  Warning! Invalid reg_update state 0
05-11 17:15:59.595 676-4734/? I/mm-camera: <CPP   >< INFO> 371: cpp_hardware_set_clock: Set clock 200000000 BW avg 141389552 BW inst 141389552
05-11 17:15:59.735 676-4734/? E/mm-camera: <CPP   ><ERROR> 434: cpp_thread_handle_process_buf_event: [CPP_BUF:] dropped frame id=7 identity=0x20002, HAL buffer not enqueued
05-11 17:16:00.391 676-4741/? E/mm-camera: <STATS_AF ><ERROR> 415: af_util_done: MainCamera=0 final lens pos 119, status=1
05-11 17:16:01.226 676-4741/? E/mm-camera: <STATS_AF ><ERROR> 415: af_util_done: MainCamera=0 final lens pos 118, status=1
05-11 17:16:01.890 676-4741/? E/mm-camera: <STATS_AF ><ERROR> 415: af_util_done: MainCamera=0 final lens pos 119, status=1
05-11 17:16:02.557 676-4741/? E/mm-camera: <STATS_AF ><ERROR> 415: af_util_done: MainCamera=0 final lens pos 118, status=1
05-11 17:16:03.157 676-4741/? E/mm-camera: <STATS_AF ><ERROR> 415: af_util_done: MainCamera=0 final lens pos 119, status=1
05-11 17:16:03.723 676-4741/? E/mm-camera: <STATS_AF ><ERROR> 415: af_util_done: MainCamera=0 final lens pos 120, status=1
05-11 17:16:04.290 676-4741/? E/mm-camera: <STATS_AF ><ERROR> 415: af_util_done: MainCamera=0 final lens pos 119, status=1
05-11 17:16:06.156 676-4741/? E/mm-camera: <STATS_AF ><ERROR> 415: af_util_done: MainCamera=0 final lens pos 120, status=1
05-11 17:16:07.333 894-905/? I/zygote64: Background concurrent copying GC freed 22450(1299KB) AllocSpace objects, 17(724KB) LOS objects, 42% free, 17MB/29MB, paused 316us total 197.359ms
05-11 17:16:07.555 676-4741/? E/mm-camera: <STATS_AF ><ERROR> 415: af_util_done: MainCamera=0 final lens pos 120, status=1
05-11 17:16:08.155 676-4741/? E/mm-camera: <STATS_AF ><ERROR> 415: af_util_done: MainCamera=0 final lens pos 121, status=1
05-11 17:16:08.788 676-4741/? E/mm-camera: <STATS_AF ><ERROR> 415: af_util_done: MainCamera=0 final lens pos 120, status=1
05-11 17:16:08.972 676-4731/? E/mm-camera: <ISP   ><ERROR> 227: isp_hw_update_util_request_reg_update: Warning! reg_cmd ioctl happened on frame boundary
05-11 17:16:09.389 676-4741/? E/mm-camera: <STATS_AF ><ERROR> 415: af_util_done: MainCamera=0 final lens pos 121, status=1
05-11 17:16:10.422 676-4741/? E/mm-camera: <STATS_AF ><ERROR> 415: af_util_done: MainCamera=0 final lens pos 120, status=1
05-11 17:16:11.055 676-4741/? E/mm-camera: <STATS_AF ><ERROR> 415: af_util_done: MainCamera=0 final lens pos 120, status=1
05-11 17:16:12.155 676-4741/? E/mm-camera: <STATS_AF ><ERROR> 415: af_util_done: MainCamera=0 final lens pos 121, status=1
05-11 17:16:12.754 676-4741/? E/mm-camera: <STATS_AF ><ERROR> 415: af_util_done: MainCamera=0 final lens pos 121, status=1
05-11 17:16:13.355 676-4741/? E/mm-camera: <STATS_AF ><ERROR> 415: af_util_done: MainCamera=0 final lens pos 120, status=1
05-11 17:16:13.956 676-4741/? E/mm-camera: <STATS_AF ><ERROR> 415: af_util_done: MainCamera=0 final lens pos 121, status=1
05-11 17:16:14.587 676-4741/? E/mm-camera: <STATS_AF ><ERROR> 415: af_util_done: MainCamera=0 final lens pos 120, status=1
05-11 17:16:15.187 676-4741/? E/mm-camera: <STATS_AF ><ERROR> 415: af_util_done: MainCamera=0 final lens pos 121, status=1
05-11 17:16:16.320 676-4741/? E/mm-camera: <STATS_AF ><ERROR> 415: af_util_done: MainCamera=0 final lens pos 119, status=1
05-11 17:16:16.920 676-4741/? E/mm-camera: <STATS_AF ><ERROR> 415: af_util_done: MainCamera=0 final lens pos 123, status=1
05-11 17:16:17.553 676-4741/? E/mm-camera: <STATS_AF ><ERROR> 415: af_util_done: MainCamera=0 final lens pos 121, status=1

**Comment by varun046** [comment]
This issue is because of improper En-queuing and De-queuing of display buffer, can be fixed in source code @ "hardware/qcom/camera/QCamera2/HAL/QCamera2HWICallbacks.cpp" .

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
