### ISSUE TITLE
How can I run in 4.4 and before

### ISSUE THREAD

**Issue by 3c** [googlesamples/android-Camera2Basic#11]
min sdk is 21

**Comment by falnatsheh** [comment]
You can't run this code below SDK 21. That's because the sample is using Camera2 APIs which was introduced in 21, you could check the deprecated [Camera APIs](http://developer.android.com/reference/android/hardware/Camera.html) for backward compatibility.

**Comment by yaraki** [comment]
This sample is specifically targeted to Android 5.0 Lollipop and later.
