### ISSUE TITLE
gradle build for project failing.

### ISSUE THREAD

**Issue by nutsiepully** [googlesamples/android-Camera2Basic#111]
The build was failing for me on a simple 'clone + build' on my machine. The build complained it couldn't find 'runtime' and was unable to find android/arch/lifecycle in jcenter.

After messing around with the gradle I was able to fix it by modifying the repositories config to put google() on top of jcenter()

It's quite odd that this should fix the problem. I would've expected the ordering of the repos to not matter.

Patch used
--
```
diff --git a/Application/build.gradle b/Application/build.gradle
index 3cdc07d..fc80b73 100644
--- a/Application/build.gradle
+++ b/Application/build.gradle
@@ -13,8 +13,8 @@ buildscript {
 apply plugin: 'com.android.application'
 
 repositories {
-    jcenter()
     google()
+    jcenter()
 }
```

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
