### ISSUE TITLE
image preview is stretched in 18:9 aspect ratio devices

### ISSUE THREAD

**Issue by rameshbabudevalingam** [googlesamples/android-Camera2Basic#113]
On running the Camera2Basic in 18:9 screen aspect ratio devices, the image preview and captured image is getting stretched.

![screenshot_camera2basic](https://user-images.githubusercontent.com/38007133/41978301-2b69bea4-7a3f-11e8-8910-ab6b3a14bc58.jpg)

I am requesting the mPreviewSize of 1440 X 1080 while the device's available resolution is 1912 X 1080.

Tried several suggestions available but none worked.

**Comment by GuanacoDevs** [comment]
Check the width and height in your xml texture view.
This is mine, had `"match_parent"` before and in my `Constraint Layout`, it is constrained to the top only, not the bottom,
```
  <com.guanacodevs.cardreader.AutoFitTextureView
        android:id="@+id/texture_view"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:backgroundTint="#000"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toTopOf="parent" />
```

**Comment by GaldinoJr** [comment]
GuanacoDevs Very nice!!

**Comment by anonym24** [comment]
@GuanacoDevs please take a look at my issue

**Comment by Tapia83** [comment]
Hy,
I've got the same problem than you.
I think is the ConstraintLayout that change the ration off the textureview, if you try a linearLayout, the probleme is gone...
If you solve it with the ConstraintLayout, please let me know...

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
