### ISSUE TITLE
flash getting fired off after the image has been clicked

### ISSUE THREAD

**Issue by ghost** [googlesamples/android-Camera2Basic#115]
i saw this bug on specific devices (Nokia 6.1, Moto X4, OnePlus 5) where when i try to click image with flash, resulting image looks like flash  was fired either before or after the image is clicked. On Lower end devices like Nokia1 ,Xiomi Note 4, Redmi note 3, Samsung J2 ,Samsung galaxy onpro5 flash is working perfectly fine.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
