### ISSUE TITLE
CreateCaptureSession() issue with Nougut OS

### ISSUE THREAD

**Issue by jagadishthadakamalla** [googlesamples/android-Camera2Basic#117]
Hello,

We have a mobile app (Andriod OS and with C#).
We can see a blank/black screen when we launch camera from the app.

The "CreateCaptureSession" works fine for the Marshmallow devices with its parameters, but it is not working properly for Nougat devices.
Can any one see this issue?
If so, please help.

**Comment by jagadishthadakamalla** [comment]
Any help here, please!!!

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
