### ISSUE TITLE
Unable to change the surface orientation of ImageReader/Allocation for repeating capture

### ISSUE THREAD

**Issue by wangcan26** [googlesamples/android-Camera2Basic#118]
I use a Surface with a SurfaceTexture and a Surface of an Allocation as the output surfaces of the CaptureRequest Builder.  They all hava a yuv_420_888 format. 

I use the SurfaceTexture to render it on SurfaceView through opengl es. I covert the allocation yuv data from the allocation to rgb data through the renderscript and copy the result data to a bitmap. They all occur every frame.

My App is in a portrait mode.

the surfaceview shows the preview in a portrait mode, however, the bitmap shows the image in a landscape mode.

I konw i can rotate the copied data from the allocation to my rotated one and send it to the bitmap, but i think its not a perfect way.

This is the same as i use an imagereader instead of an allocation

Is there a way to change the surface orientation in my case?

Thanks and appreciate for your answer!

**Comment by wangcan26** [comment]
Maybe I think the best way to rotate the surface of the Allocation is through the renderscript. And The ImageReader not appropriate for preview

**Comment by syakimchik** [comment]
Hello,
Could you please explain how you are getting every frame from SurfaceView? But now, I cannot find any way to get frames from Surface View the same it was implemented into Camera1 API.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
