### ISSUE TITLE
image preview is stretched in galaxy note 10.1 SMP600

### ISSUE THREAD

**Issue by KeyurEww** [googlesamples/android-Camera2Basic#119]
It is working on some devices but Samsung  Galaxy Note 10.1 SMP600, it is stretching preview size. I debug and found that It is not getting bigEnough size, and taking from notBigEnough size. I dont understand what is issue.

**Comment by damaro333** [comment]
I am also having this problem with my Galaxy Tab A 10.1" - 1920x1200 is the original solution. TextureView Ratio and size is set to 1920:1080 because I need 16:9 pictures and because the camera has no full screen functionality. The delay before opening also does not help.

**Comment by drayan85** [comment]
+1

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
