### ISSUE TITLE
Be Stuck with two problems: ClassNotFoundException and hardware acceleration is not enabled.

### ISSUE THREAD

**Issue by GlennLin** [googlesamples/android-Camera2Basic#12]
Hi everyone:

  I'm new comer for Android application development.
  Just let somebody know if they are stuck in two issues:

I. AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.example.android.camera2basic.CameraActivity" on path: DexPathList[[zip file "/data/app/com.example.android.camera2basic-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]

I move source codes location from

.\android-Camera2Basic-master\Application\src\main\java\com\example\android\camera2basic

to 
.\android-Camera2Basic-master\Application\src\main\src\com\example\android\camera2basic

Then solve the first problem.

II. TextureView: A TextureView or a subclass can only be used with hardware acceleration enabled.

I add below settings into AndroidManifest.xml to resolve the error.

    <uses-sdk
        android:minSdkVersion="21"
        android:targetSdkVersion="21" />

    <application android:allowBackup="true"
        android:label="@string/app_name"
        android:icon="@drawable/ic_launcher"
        android:theme="@style/MaterialTheme"
		android:hardwareAccelerated="true">

  Now I can test the camera API 2 with this application. It's really helpful. Thanks.

BR.

**Comment by yaraki** [comment]
The first problem seems to be an issue with your build environment. The hardware acceleration is on by default, so there should be no need for that attribute.
