### ISSUE TITLE
addPicToGallery() is not working

### ISSUE THREAD

**Issue by VIkash2601** [googlesamples/android-Camera2Basic#120]
Hi, I'm facing some issues while running this code on MI Y2. As soon as I captured the image it is saved into the root folder but each time the new image is saved with the same name i.e. overwrites the previous image. On the other hand, as I open the image it says file format is not supported.

Please help me to figure out this issue. **Also I want to store each image with a different name.**

Here is the code to add to gallery:
 `
private void addPicToGallery() {`
 `        Intent mediaScanIntent = new Intent(Intent.ACTION_MEDIA_SCANNER_SCAN_FILE);`
   `      Uri contentUri = Uri.fromFile(mFile);`
     `    mediaScanIntent.setData(contentUri);`
       `  getActivity().sendBroadcast(mediaScanIntent);`
    ` }
`
Here I'm saving the image with a random name:
`final String uniqueID = "image_"+ UUID.randomUUID().toString().replace("-","")+".jpg";`
`        mFile = new File(getActivity().getExternalFilesDir(null), uniqueID);
`

**Comment by n0lik** [comment]
Hi. I think that your contentUri is incorrect. [See this.](https://stackoverflow.com/questions/18249007/how-to-use-support-fileprovider-for-sharing-content-to-other-apps)

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
