### ISSUE TITLE
possible to mix image/video take?

### ISSUE THREAD

**Issue by suarezu** [googlesamples/android-Camera2Basic#122]
and set aspect ratio/resolution dynamically along with other common camera operations?

I failed to integrate android-Camera2Basic and android-Camera2Video into one library. I want a preview of camera capable of both image taken and video recording with specified resolution.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
