### ISSUE TITLE
Fatal signal 11 (SIGSEGV), code 1, fault addr 0x10148 in tid 13013 (RenderThread)

### ISSUE THREAD

**Issue by yangdengxueshi** [googlesamples/android-Camera2Basic#124]
I've down a test,only in "onResume" to getBitmap circularly,about 15 minutes later,I encountered this Exception.

What's wrong with this? 

I want to getBitmap in real time.

Error: 
09-18 09:45:31.333 2157-2188/com.example.android.camera2basic A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x74756f796294 in tid 2188 (RenderThread)

![crash3](https://user-images.githubusercontent.com/25955707/45659550-a881d600-bb27-11e8-9cc0-761770f1a11d.png)

**Comment by Satheeshkummari** [comment]
Yes i too got the same exception while accessing bitmap from AutoFitTextureView continuously
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xc000041d80050 in tid 27323 (RenderThread).
getBitmap() is not thread safe ?

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
