### ISSUE TITLE
Camera Stop Work After Capturing Multiple Images Periodically

### ISSUE THREAD

**Issue by liute62** [googlesamples/android-Camera2Basic#125]
Hi guys,

  I find a problem that If I call "takePicture" function multiple times periodically, the app works well at the beginning, but it is frozen after multiple capturing. As a result, the camera stops improperly and the app can't be opened again without restart the phone.

Here is the only code I added for the Camera2BasicFragment:

  Observable.intervalRange(0,1000,1,1,TimeUnit.SECONDS).
                        subscribe(
                                new Consumer<Long>() {
                                    @Override
                                    public void accept(Long aLong) throws Exception {
                                        takePicture();
                                    }
                                }
                        );
Namely create a counter and for every 1 second, it calls takePicture function.

Look forward to your help, thanks!

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
