### ISSUE TITLE
Auto Focus Mode -- Focus Distance 

### ISSUE THREAD

**Issue by AswinVasudevan21** [googlesamples/android-Camera2Basic#127]
I am trying to calculate LENS_FOCUS_DISTANCE using Capture Result but when I get the focusValue(distance) as shown below its always 0.0. 

PS: Its is not a device compatible issue.  

```
final CameraCaptureSession.CaptureCallback captureListener = new CameraCaptureSession.CaptureCallback() {
                @Override
                public void onCaptureCompleted(CameraCaptureSession session, CaptureRequest request, TotalCaptureResult result) {
                    super.onCaptureCompleted(session, request, result);
                    createCameraPreview();

                    focusValue = result.get(CaptureResult.LENS_FOCUS_DISTANCE);
                }

```

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
