### ISSUE TITLE
Galaxy Tab A 10.1 preview skewed

### ISSUE THREAD

**Issue by damaro333** [googlesamples/android-Camera2Basic#128]
I am having a problem with the preview of my Galaxy Tab A 10.1" - 1920x1200 is the original solution. AutoFitTextureView Ratio and size is set to 1920:1080 because I need 16:9 pictures and because the camera has no full screen functionality - The native camera also shots in 16:9. A delay before opening the camera also does not help.

Working with: Galaxy Note 8 - 18,5:9 and with Galaxy J5 16:9 both with 16:9 pictures...No skewed images...

Someone had the same prob?

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
