### ISSUE TITLE
Missing Manifest premissions entry to write to external storage location

### ISSUE THREAD

**Issue by CKehl** [googlesamples/android-Camera2Basic#13]
Hi guys,

I just pulled the example after some time again from the repo (wanted to see about updates), imported the project into Android Studio, ran the app - but the pic.jpg didn't get stored. 

06-19 13:18:58.165  25887-28705/com.example.android.camera2basic W/System.err﹕ java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.example.android.camera2basic/files/pic.jpg: open failed: EACCES (Permission denied)
06-19 13:18:58.165  25887-28705/com.example.android.camera2basic W/System.err﹕ at libcore.io.IoBridge.open(IoBridge.java:456)
06-19 13:18:58.165  25887-28705/com.example.android.camera2basic W/System.err﹕ at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
06-19 13:18:58.165  25887-28705/com.example.android.camera2basic W/System.err﹕ at java.io.FileOutputStream.<init>(FileOutputStream.java:72)
06-19 13:18:58.166  25887-28705/com.example.android.camera2basic W/System.err﹕ at com.example.android.camera2basic.Camera2BasicFragment$ImageSaver.run(Camera2BasicFragment.java:795)
06-19 13:18:58.166  25887-28705/com.example.android.camera2basic W/System.err﹕ at android.os.Handler.handleCallback(Handler.java:739)
06-19 13:18:58.166  25887-28705/com.example.android.camera2basic W/System.err﹕ at android.os.Handler.dispatchMessage(Handler.java:95)
06-19 13:18:58.166  25887-28705/com.example.android.camera2basic W/System.err﹕ at android.os.Looper.loop(Looper.java:135)
06-19 13:18:58.166  25887-28705/com.example.android.camera2basic W/System.err﹕ at android.os.HandlerThread.run(HandlerThread.java:61)
06-19 13:18:58.166  25887-28705/com.example.android.camera2basic W/System.err﹕ Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
06-19 13:18:58.166  25887-28705/com.example.android.camera2basic W/System.err﹕ at libcore.io.Posix.open(Native Method)
06-19 13:18:58.166  25887-28705/com.example.android.camera2basic W/System.err﹕ at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
06-19 13:18:58.166  25887-28705/com.example.android.camera2basic W/System.err﹕ at libcore.io.IoBridge.open(IoBridge.java:442)

obviously, the WRITE_EXTERNAL_STORAGE permission could get rid of the problem. The issue occurred on my NVIDIA Shield tablet, SDK version 22, with sdcard attached. Anybody else experiencing similar problems ?

**Comment by yaraki** [comment]
The sample is using `getExternalFilesDir`, so there should be no need for that permission. Do you have issues with other apps that use getExternalFilesDir on your device?

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
