### ISSUE TITLE
Crashes on Google Pixel 2 and 2 XL

### ISSUE THREAD

**Issue by DrAxeY** [googlesamples/android-Camera2Basic#131]
Recently the app crashes on image capturing but only on Google Pixel 2 and Pixel 2 XL devices.

Crash report shows the following:
```
java.lang.NullPointerException: 
  at ....Camera2BasicFragment$ImageSaver.run (Camera2BasicFragment.java:935)
  at android.os.Handler.handleCallback (Handler.java:873)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:193)
  at android.os.HandlerThread.run (HandlerThread.java:65)
```

This is line 935 (ImageSaver class):
`ByteBuffer buffer = mImage.getPlanes()[0].getBuffer();`

I've tried a few things but I'm unable to test as I do not have a Pixel 2 device. Any suggestions?

Update (06-Nov-2018):

So the logical explanation is that the image being returned from the ImageReader is somehow null:

```
@Override
        public void onImageAvailable(ImageReader reader) {
            mBackgroundHandler.post(new ImageSaver(reader.acquireLatestImage(), mFile));
        }
```

Some other posts suggest that the ImageReader format may not be supported. This is the format:

```
mImageReader = ImageReader.newInstance(largest.getWidth(), largest.getHeight(),
 ImageFormat.JPEG, /*maxImages*/2);
```

But I can't imagine why JPEG would be an unsupported format.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
