### ISSUE TITLE
can't import

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [googlesamples/android-Camera2Basic#132]
I get this:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':Application'.
> No toolchains found in the NDK toolchains folder for ABI with prefix: mips64el-linux-android

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

CONFIGURE FAILED in 1m 6s
No toolchains found in the NDK toolchains folder for ABI with prefix: mips64el-linux-android
```

![image](https://user-images.githubusercontent.com/5357526/48551505-659d6e00-e8de-11e8-8521-878f298ccfe0.png)

**Comment by Md-Mahfuzur-Rahman** [comment]
i m also facing this issue :(

**Comment by elmirjagudin** [comment]
To build the app with Android Studio 3.2.1 I had to change:

in Application/build.gradle:

    buildscript {
        <.. snip ..>
        dependencies {
            classpath 'com.android.tools.build:gradle:3.2.1'
        }
    }

    android {
        <.. snip ..>

        buildToolsVersion "28.0.3"

        <.. snip ..>
    }

and in gradle/wrapper/gradle-wrapper.properties:

    distributionUrl=https\://services.gradle.org/distributions/gradle-4.6-all.zip

Here is the full patch of the changes:

~~~
diff --git a/Application/build.gradle b/Application/build.gradle
index 3cdc07d..cc0f984 100644
--- a/Application/build.gradle
+++ b/Application/build.gradle
@@ -6,7 +6,7 @@ buildscript {
     }
 
     dependencies {
-        classpath 'com.android.tools.build:gradle:3.0.1'
+        classpath 'com.android.tools.build:gradle:3.2.1'
     }
 }
 
@@ -35,7 +35,7 @@ List<String> dirs = [
 android {
     compileSdkVersion 27
 
-    buildToolsVersion "27.0.2"
+    buildToolsVersion "28.0.3"
 
     defaultConfig {
         minSdkVersion 21
diff --git a/gradle/wrapper/gradle-wrapper.properties b/gradle/wrapper/gradle-wrapper.properties
index 86fc139..9cd76d8 100644
--- a/gradle/wrapper/gradle-wrapper.properties
+++ b/gradle/wrapper/gradle-wrapper.properties
@@ -3,4 +3,4 @@ distributionBase=GRADLE_USER_HOME
 distributionPath=wrapper/dists
 zipStoreBase=GRADLE_USER_HOME
 zipStorePath=wrapper/dists
-distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip
\ No newline at end of file
+distributionUrl=https\://services.gradle.org/distributions/gradle-4.6-all.zip
~~~

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
