### ISSUE TITLE
Image not being captured in Android Emulator API 28

### ISSUE THREAD

**Issue by hrishikesh-kadam** [googlesamples/android-Camera2Basic#140]

**Comment by MarioDiar** [comment]
Any ideas on what could be causing this? I am having issues aswell.

**Comment by JanvanZetten** [comment]
I had an issue with the Emulator but that is at least also version 27. The problem for me was that the virtual scene camera does not have autofocus so when it waits for focus it will never happen. 
I fixed this by adding `|| afState == CaptureResult.CONTROL_AF_STATE_INACTIVE` in the `mCaptureCallback` under the case `STATE_WAITING_LOCK:` in the if statement which looks like `if (afState == null)` in the original version. It should look like this:
` if (afState == null || afState == CaptureResult.CONTROL_AF_STATE_INACTIVE)`

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
