### ISSUE TITLE
Not Getting clear image in Lenovo Tablet Versions

### ISSUE THREAD

**Issue by chandruark** [googlesamples/android-Camera2Basic#142]
Device: Lenovo Tab 
Model : Lenovo TB-8504X

Issues in Android Tab: 
While Camera Opens in Tab Version, It becomes blurry and unclear in the Image Content

I have attached the Image for Both Camera 2 Implementation Img and Device Default Camera Img

1)**Camera 2 Implementation Img**
![photo_2019-02-16_19-46-29](https://user-images.githubusercontent.com/26240872/52901091-72ef2f00-3224-11e9-9a0c-4cad59f7398c.jpg)

2)**Default Camera Implementation**
![photo_2019-02-16_19-48-37](https://user-images.githubusercontent.com/26240872/52901042-f0ff0600-3223-11e9-9d3c-102eea9042da.jpg)

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
