### ISSUE TITLE
InstanceCountViolation

### ISSUE THREAD

**Issue by BulatMukhutdinov** [googlesamples/android-Camera2Basic#145]
If we will add
```
 StrictMode.setThreadPolicy(
                StrictMode.ThreadPolicy.Builder()
                        .detectAll()
                        .penaltyLog()
                        .penaltyDeath()
                        .build()
        )

        StrictMode.setVmPolicy(StrictMode.VmPolicy.Builder()
                .detectAll()
                .penaltyLog()
                .penaltyDeath()
                .build()
        )
```
to CameraActivity's onCreate() method and start rotating a device after second rotation it will crash with  
```
StrictMode policy violation: android.os.strictmode.InstanceCountViolation: class com.example.android.camera2basic.CameraActivity; instances=2; limit=1
```

**Comment by BulatMukhutdinov** [comment]
Most probable issue is in
```
 displayManager = viewFinder.context
                .getSystemService(Context.DISPLAY_SERVICE) as DisplayManager
```

if you would not keep displayManager as class filed but as local variable instead it would help to avoid memory leak

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
