### ISSUE TITLE
 android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): submitRequestList:283

### ISSUE THREAD

**Issue by gordanxu** [googlesamples/android-Camera2Basic#148]
android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): submitRequestList:283: Camera 0: Got error Invalid argument (-22) after trying to submit capture request

荣耀 V8的手机 Android 8.0 系统 拍照报错,后来发现将方法中代码修改下 才正常 特此记录下

private void captureStillPicture() {
......
//mCaptureSession.stopRepeating();
            //mCaptureSession.abortCaptures();
           // mCaptureSession.capture(captureBuilder.build(), CaptureCallback, null);
//更换为下面的代码
            mCaptureSession.setRepeatingRequest(captureBuilder.build(), CaptureCallback,mBackgroundHandler);
}

**Comment by ngocphung247** [comment]
add it before call mCaptureSession.capture to resolve your problem
if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.N){
    mCaptureSession.stopRepeating();
    mCaptureSession.abortCaptures();
}

**Comment by gordanxu** [comment]
Thanks,Very Much!

**Comment by gordanxu** [comment]
i have a try ,but it doesn`t work!!!

**Comment by ngocphung247** [comment]
can you paste your function captureStillPicture() here ?

**Comment by gordanxu** [comment]
CaptureRequest.Builder mBuilder=mCameraDevice.createCaptureRequest(CameraDevice.TEMPLATE_STILL_CAPTURE);
                    mBuilder.addTarget(mImageReader.getSurface());
                    mBuilder.set(CaptureRequest.CONTROL_AF_MODE, CaptureRequest.CONTROL_AF_MODE_CONTINUOUS_PICTURE);
                    mBuilder.set(CaptureRequest.CONTROL_AE_MODE,CaptureRequest.CONTROL_AE_ANTIBANDING_MODE_AUTO);

                    CameraCaptureSession.CaptureCallback tempCallBack=new CameraCaptureSession.CaptureCallback() {
                        @Override
                        public void onCaptureStarted( CameraCaptureSession session,CaptureRequest request, long timestamp, long frameNumber) {
                            super.onCaptureStarted(session, request, timestamp, frameNumber);

                            Log.i(TAG,"====2======onCaptureStarted()");
                        }

                        @Override
                        public void onCaptureProgressed( CameraCaptureSession session,CaptureRequest request,CaptureResult partialResult) {
                            super.onCaptureProgressed(session, request, partialResult);

                            Log.i(TAG,"====2======onCaptureProgressed()");
                        }

                        @Override
                        public void onCaptureCompleted( CameraCaptureSession session,CaptureRequest request,TotalCaptureResult result) {
                            super.onCaptureCompleted(session, request, result);
                            Log.i(TAG,"====2======onCaptureCompleted()");

                            unlockFocus();
                        }
                    };

                    if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.N){
                        mCameraCaptureSession.stopRepeating();
                        mCameraCaptureSession.abortCaptures();
                    }
                    mCameraCaptureSession.capture(mBuilder.build(), tempCallBack, null);

**Comment by ngocphung247** [comment]
try remove mCameraCaptureSession.abortCaptures();
it becomes:
...
mCameraCaptureSession.stopRepeating();               
mCameraCaptureSession.capture(mBuilder.build(), tempCallBack, null);

**Comment by ngocphung247** [comment]
Ah no, I have a little confused, you can change >= to < Build.VERSION_CODES.N . =))

**Comment by ngocphung247** [comment]
Because if you run on devices 8.0.0, my old code will not change anything =)) Sorry guys. But you try to only remove mCameraCaptureSession.abortCaptures(); as my above comment =))

**Comment by ngocphung247** [comment]
....
if (android.os.Build.VERSION.SDK_INT < android.os.Build.VERSION_CODES.N){
                    mCameraCaptureSession.stopRepeating();
                    mCameraCaptureSession.abortCaptures();
                }
                mCameraCaptureSession.capture(mBuilder.build(), tempCallBack, null);
or
....
mCameraCaptureSession.stopRepeating();
mCameraCaptureSession.capture(mBuilder.build(), tempCallBack, null);
will run :))

**Comment by gordanxu** [comment]
Thanks,Very Much! it works! :)
