### ISSUE TITLE
 The application falls on huawei  p8 lite 2017 

### ISSUE THREAD

**Issue by KonstantinProgram** [googlesamples/android-Camera2Basic#149]
E/MediaRecorder: stop failed: -1007 
`mediaRecorder?.apply {
                    stop()
                    reset()
                }`

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
