### ISSUE TITLE
AutoFitTextureView capture's a frame that is not visible in camera preview

### ISSUE THREAD

**Issue by keval02** [googlesamples/android-Camera2Basic#150]
In my layout texture view is in center and there are some views in top and also on bottom of texture view. When i am capturing an image the photo contains even that frame which was not visible in preview. I have followed all the steps of camera 2 api. But it still captures the frame that is not visible in camera preview.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
