### ISSUE TITLE
Usable API?

### ISSUE THREAD

**Issue by rdehuyss** [googlesamples/android-Camera2Basic#152]
The guys who wrote the Camera2 api should **REALLY** read the google PDF 
**How to Design a Good API and Why it Matters** https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/32713.pdf

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
