### ISSUE TITLE
I/swiftshader: lock failed: buffer of 640x480 too small for window of 480x640

### ISSUE THREAD

**Issue by KhyatiMehta3** [googlesamples/android-Camera2Basic#153]
Tried this app out of the box, without making any changes and the preview just keeps flickering & this message keeps popping up in the logcat. 
`I/swiftshader: lock failed: buffer of 640x480 too small for window of 480x640`
This is being tried out on an emulator Nexus S Api 22

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
