### ISSUE TITLE
Image gets rotated by 90 degrees left

### ISSUE THREAD

**Issue by DeepanJN** [googlesamples/android-Camera2Basic#154]
The image gets rotated by 90 degrees left. Anyone facing this issue?

**Comment by harry-048** [comment]
I have this issue too, I didn't solve it. But i found a method. Save the image on a bitmap and check the height and width, if width is greater than height then image is rotated, then you have to rotate that bitmap using cavas. Hope it helps you too.

**Comment by vaibnak** [comment]
I used the matrix in android to rotate the bitmap by 90 deg post its extraction from image. Here is its code -
`                   Matrix matrix = new Matrix();
                    matrix.postRotate(90);
                    Bitmap rotatedBitmap = Bitmap.createBitmap(resbmp, 0, 0, resbmp.getWidth(), resbmp.getHeight(), matrix, true);`

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
