### ISSUE TITLE
Native memory usage keeps increasing without interference in the Profiler

### ISSUE THREAD

**Issue by brianxcli** [googlesamples/android-Camera2Basic#156]
Run the demo and watch the memory usage using Android Profiler in AS. 

As the time goes, the memory of the demo will not stop increasing mainly because the trend of native memory usage. 

It is not actually a memory leak, and as long as the Force GC is triggered, the native memory gets back to normal level, the same cycle repeating. So it is nothing but the garbage collection is not executed as the way we think.  However, it leaves a problem when we want to evaluate and compare the performance of apps, and when we may not be able to trigger a garbage collection. One solution I am using now is running runtime gc in the capture result callback after every, say, 50 frames captured and drawn.

It ends up with the memory maintaining at a low level, but leaving an explicit concurrent gc log every collection. That seems not desirable for a production. 

Any suggestion for that? I am using Honor V20, Android 9.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
