### ISSUE TITLE
Error Take photo xaomi 

### ISSUE THREAD

**Issue by maximopiu18** [googlesamples/android-Camera2Basic#159]
when a photo is taken in a xaomi A1, the image is not saved and afterwards it doesn´t take any more photos

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
