### ISSUE TITLE
why saved twice?

### ISSUE THREAD

**Issue by suyoung21** [googlesamples/android-Camera2Basic#160]
first in app,take a picture,
log:
`2019-09-09 15:27:43.867 22484-22506/com.example.android.camera2basic D/Camera2BasicFragment: /storage/emulated/0/Android/data/com.example.android.camera2basic/files/pic.jpg`

press the btn again,take a picture,
log:
`2019-09-09 15:27:47.836 22484-22506/com.example.android.camera2basic D/Camera2BasicFragment: /storage/emulated/0/Android/data/com.example.android.camera2basic/files/pic.jpg
2019-09-09 15:27:47.874 22484-22506/com.example.android.camera2basic D/Camera2BasicFragment: /storage/emulated/0/Android/data/com.example.android.camera2basic/files/pic.jpg`

why execute twice?

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
