### ISSUE TITLE
TextureView sometimes does not fit properly while switching between landscape and portrait mode

### ISSUE THREAD

**Issue by agamgoyal876** [googlesamples/android-Camera2Basic#161]
Sometimes on relaunching camera activity, TextureView covers only half area of screen in portrait mode as if it were opened in landscape mode and vice versa. 

This issue is also visible when configuration changes are handled manually for camera Activity and we rotate screen while camera preview is visible.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
