### ISSUE TITLE
App closes immediately when checking for permissions.

### ISSUE THREAD

**Issue by JackLClements** [googlesamples/android-Camera2Basic#22]
When running on a Galaxy S6 (Lollipop) , the app checks for permission to use the camera in an if statement and immediately crashes. Not sure why this is.

**Comment by gorjuspixels** [comment]
@JackLClements i had the same problem, just use support library v4 - `ContextCompat.checkSelfPermission(getActivity(), Manifest.permission.CAMERA)  != PackageManager.PERMISSION_GRANTED`

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
