### ISSUE TITLE
Crashes on devices without flash

### ISSUE THREAD

**Issue by cheidenreich** [googlesamples/android-Camera2Basic#23]
On my Sony Xperia Z4 Tablet (which has no builtin flash on the backside) this demo crashes without any useful stacktrace whatsoever. After commenting out 

``` java
mPreviewRequestBuilder.set(CaptureRequest.CONTROL_AE_MODE, CaptureRequest.CONTROL_AE_MODE_ON_AUTO_FLASH);
```

in Camera2BasicFragment.java line 695 it works fine.

//EDIT:
also in 

``` java
private void unlockFocus()
```

and 

``` java
private void captureStillPicture()
```

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
