### ISSUE TITLE
Nexus 5x captured image is inverted

### ISSUE THREAD

**Issue by gbero** [googlesamples/android-Camera2Basic#24]
When taking a picture using a Nexus 5x the picture is inverted (upside down)
I was looking for a fix regarding this issue here since it's Google sample :)

**Comment by keyboardsurfer** [comment]
Are you using this sample's source code to take the picture?

**Comment by gbero** [comment]
Yes I am.

It looks like doing :

CameraManager manager = (CameraManager) getContext().getSystemService(Context.CAMERA_SERVICE);
      CameraCharacteristics cameraCharacteristics = manager.getCameraCharacteristics("" + mCameraDevice.getId());
      int rotation = cameraCharacteristics.get(CameraCharacteristics.SENSOR_ORIENTATION);
      captureBuilder.set(CaptureRequest.JPEG_ORIENTATION, rotation);

fixes the issue (at least on Nexus 5 and Nexus 5x)

**Comment by gbero** [comment]
Do you want me to submit a PR with this ?

**Comment by gbero** [comment]
@keyboardsurfer any progress on this ? I can't figure out how to do this right. I'm getting problem on Galaxy S6 which has inverted picture... :(

**Comment by yaraki** [comment]
Hi, @gbero .
Please use the formula below instead of `ORIENTATIONS.get(rotation)`.

    private int getOrientation(int rotation) {
        return (ORIENTATIONS.get(rotation) + mSensorOrientation + 270) % 360;
    }

I'm applying this change to the sample soon.

**Comment by UMFsimke** [comment]
Hi @yaraki,

I've tested your

`private int getOrientation(int rotation) {
    return (ORIENTATIONS.get(rotation) + mSensorOrientation + 270) % 360;
}`

method and its not working on Nexus 5x on Back camera. Image is still rotated in final output. If you take portrait image it will save it rotated for 90 degrees. On the other side @gbero 's solution works perfectly on Nexus 5X.

**Comment by gbero** [comment]
@yaraki I'm getting complaints from users with Nexus 6 that FFC picture is inverted and can't figure out how to handle it. Could Google come up with a sample tested on at least devices like N5, N5x, N6 and N6p both front and rear camera ?

**Comment by Tooroop** [comment]
Any update here?

**Comment by alistairbrightec** [comment]
Any news on this front? Having the same issue.

**Comment by Tooroop** [comment]
I think I fixed this issue but I'm not 100% sure if this is the best fix. I got the sensor orientation from the camera characteristics and then I just added an ExifInterface with the desired fixed orientation. Like this:

`  Integer sensorOrientation = characteristics.get(CameraCharacteristics.SENSOR_ORIENTATION);
                        if (sensorOrientation != null) {
                            switch (sensorOrientation) {
                                case 90:
                                    exif.setAttribute(ExifInterface.TAG_ORIENTATION, String.valueOf(ExifInterface.ORIENTATION_ROTATE_90));
                                    break;
                                case 180:
                                    exif.setAttribute(ExifInterface.TAG_ORIENTATION, String.valueOf(ExifInterface.ORIENTATION_ROTATE_180));
                                    break;
                                case 270:
                                    exif.setAttribute(ExifInterface.TAG_ORIENTATION, String.valueOf(ExifInterface.ORIENTATION_ROTATE_270));
                                    break;
                            }
                            exif.saveAttributes();`

**Comment by ajayld** [comment]
How to rotate for video capture?

**Comment by HenningL** [comment]
Is there a solution for video preview? Cant find anything to solve it.

**Comment by dreimanis** [comment]
Still with this fix. I have an issues with it. 
On the Phone the Images looks fine. But when I send them with email to my PC. (In preview they still look fine.) Once it's on my pc , it's rotated -90. 
From 3 phones that I have LGG4, Samsung J7 and Sony Experia (something). 
Only works on the LGG4 ( and it takes 16:9 images , others take 4:3).

I don't think its Windows fault, because when I capture the image and save it. Then load it on a ImageView , its rotated.

**Comment by talalz94** [comment]
The pictures are not being saved ?

**Comment by shashwattt-Pretlist** [comment]
Same for me, it is working fine on Pixel, Oppo, Micromax, Gionee but is rotated -90 degree on Samsung, can any one suggest a fix .. please

**Comment by aleksamarkoni** [comment]
I have the same problem. The picture in preview mode is rotated -90. I could not find how to fix this except for checking if it's Samsung phone and then rotating the picture my self. I thought that this Camera 2 api's should be much easier to use, but they introduce so many problems that you did not had with Camera 1. And what is worse, there is no real feedback or solution for this problem, in like one year now, with so many people complaining.

**Comment by NagoorBabu** [comment]
Can somebody tell, How to calculate JPEG_ORIENTATION for front camera? I used (ORIENTATIONS.get(rotation) + mSensorOrientation + 270) % 360; for back camera. which is working just fine.

**Comment by sohambannerjee8** [comment]
Not Working for Front Camera.Tested on S5(Samsung).

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
