### ISSUE TITLE
i am geting error on import android.support.v13.app.FragmentCompat;  

### ISSUE THREAD

**Issue by KathiravanRK** [googlesamples/android-Camera2Basic#25]
i am geting error on import android.support.v13.app.FragmentCompat;  
lib the support is not suites me i am using sdk 21 -23 
please provide alternate which supports support.v4 or v7 app compats

**Comment by limitlessisa** [comment]
https://stackoverflow.com/questions/33220233/cannot-resolve-symbol-fragmentcompat

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
