### ISSUE TITLE
Preview freezes With AddTarget

### ISSUE THREAD

**Issue by Iqra786** [googlesamples/android-Camera2Basic#28]
Hi, I want to get live stream from the camera. For this purpose I am adding 
mPreviewBuilder.addTarget(mImageReader.getSurface) line of code in Camera2Basic example just after the first Target. After Adding the second target.  It Freezes the camera view and doesn't go to call back onImageAvailable(ImageReader reader) after three images. What I am doing wrong I couldn't figure out. How can I get video stream frame like Camera One setOnPreviewCallback.

**Comment by James665** [comment]
In my case image freezes when I try to switch between cameras or when have incoming videocall when device screen is locked

**Comment by RoundSparrow** [comment]
My experience with the Camera2 API is that it freezes like this on Android 6.0 (Nexus 5) and Android N preview (Nexus 6).

Some references on the topic:

            1.  https://code.google.com/p/android/issues/detail?id=79837
            2.  https://code.google.com/p/android/issues/detail?id=95757
            3.  http://stackoverflow.com/questions/34664131/camera2-imagereader-freezes-repeating-capture-request
            4.  https://github.com/commonsguy/cwac-cam2/commit/5be7efc164604c5fa2926c697bcd1f371ddce6e3 <-- Interesting, delay might help?

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
