### ISSUE TITLE
Image is always unavailable in ImageReader on Le note3(xiaomi company)

### ISSUE THREAD

**Issue by djjowfy** [googlesamples/android-Camera2Basic#29]

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
