### ISSUE TITLE
Face detection only work when ORIENTATION is Landscape

### ISSUE THREAD

**Issue by ShaunXia** [googlesamples/android-Camera2Basic#31]
the Face detection works when I set the request mode: STATISTICS_FACE_DETECT_MODE_FULL
but the question is, face detection only work when I turn screen 90 degree. 

How can I make it work when the screen is portrait which means rotate the original camera image for face detect.  Thanks..

**Comment by carlosalfonso2014** [comment]
Have you result the issue?

**Comment by ShaunXia** [comment]
I have to use the old camera API.

**Comment by carlosalfonso2014** [comment]
I'm furiouss with the new android api xS. Onfacedetectionlistener never should be deprecated.

Thanks

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
