### ISSUE TITLE
Bug:  Only fires the flash and saves a picture once

### ISSUE THREAD

**Issue by jonsutherland** [googlesamples/android-Camera2Basic#32]
Hi,

I've run into a problem where the Camara2Basic app will only save a picture the first time only when the flash fires.  After successfully saving this first picture (with flash), the preview then becomes really dark and then won't save any more pictures. 

The device I'm testing is a Nexus 6P with Android 6.0.1 (Jan 1st security patch).

I think I've found the cause of the issue.  It seems to be related to resetting the AE precapture trigger after in unlockFocus().  I'm not sure if resetting AE precapture in unlockFocus() is the proper way to fix the problem, but I've attached my patch in case anyone is interested.

[camera2basic_ae_trigger_reset.patch.txt](https://github.com/googlesamples/android-Camera2Basic/files/114863/camera2basic_ae_trigger_reset.patch.txt)

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
