### ISSUE TITLE
onCaptureCompleted have never been called

### ISSUE THREAD

**Issue by ashomokdev** [googlesamples/android-Camera2Basic#33]
I tested this app on my Sony Xperia M2, API 22 and the method onCaptureCompleted have never been called.
I have fixed this issue with adding few else statement - see the end of this part of code:

```
  private void process(CaptureResult result) {
            switch (mState) {
                case STATE_PREVIEW: {
                    // We have nothing to do when the camera preview is working normally.
                    break;
                }
                case STATE_WAITING_LOCK: {
                    Integer afState = result.get(CaptureResult.CONTROL_AF_STATE);
                    if (afState == null) {
                        captureStillPicture();
                    } else if (CaptureResult.CONTROL_AF_STATE_FOCUSED_LOCKED == afState ||
                            CaptureResult.CONTROL_AF_STATE_NOT_FOCUSED_LOCKED == afState) {
                        // CONTROL_AE_STATE can be null on some devices
                        Integer aeState = result.get(CaptureResult.CONTROL_AE_STATE);
                        if (aeState == null ||
                                aeState == CaptureResult.CONTROL_AE_STATE_CONVERGED) {
                            mState = STATE_PICTURE_TAKEN;
                            captureStillPicture();
                        } else {
                            runPrecaptureSequence();
                        }
                    }

//ADDED BY ME
                    else {
                        captureStillPicture();
                    }

                    break;
```

What can be wrong?

**Comment by drkpoon** [comment]
I have similar issue.  It turns out that my camera does not support auto focus.  The afState always equal CaptureResult.CONTROL_AF_STATE_INACTIVE.  It remains in STATE_WAITING_LOCK.

**Comment by RoundSparrow** [comment]
Same problem:  Huawei Y538, Android 5.1.1, API 22.  CaptureResult.CONTROL_AF_STATE_INACTIVE == afState

Worst the app goes into a tight loop. It should detect the failure and shift to an error state and show a toast?

**Comment by umbrella-alexander-ageychenko** [comment]
Same issue on Galaxy S6, but only when flash mode is set to 
```
requestBuilder.set(CaptureRequest.CONTROL_AE_MODE,
                        CaptureRequest.CONTROL_AE_MODE_ON_ALWAYS_FLASH);
```
when flash mode is set to 
```
requestBuilder.set(CaptureRequest.FLASH_MODE,
                        CaptureRequest.FLASH_MODE_OFF);
```
`onCaptureCompleted` is called

**Comment by Ghedeon** [comment]
Same here. OnePlus One, 6.0.1
It just randomly skips capturing. So, it successfully takes a few pictures, then on the next attempt `afState == 2` and infinite loop is started until you click again.

**Comment by lytcom** [comment]
Sometimes, afState  always ==2 in some devices.
I fix it use timeout to call captureStillPicture().

**Comment by nishu0808** [comment]
Fixed the issue by adding this condition     CaptureResult.CONTROL_AF_MODE_AUTO== afState) in else if statement. This also fixes the autoflash issue.

**Comment by JeetSingh4** [comment]
@nishu0808  Please elaborate

**Comment by delacrixmorgan** [comment]
There's a few reasons.

a) While you are `capturePicture()`, the AutoFocus state is stucked at `CONTROL_AF_STATE_PASSIVE_FOCUSED` and there is no way to shake it off.

Thus, you'll need to manually restart the focus and get a lock on it again.

b) `setRepeatingRequest()` from `captureSession` is overwhelming it. 

To resolve that, you'll need to add a delay.

Step 1 - Restructure `capturePicture(result: CaptureResult)`

```kotlin
private fun capturePicture(result: CaptureResult) {
    val afState = result.get(CaptureResult.CONTROL_AF_STATE)
    when (afState) {
        CaptureResult.CONTROL_AF_STATE_FOCUSED_LOCKED, CaptureResult.CONTROL_AF_STATE_NOT_FOCUSED_LOCKED -> {
            val aeState = result.get(CaptureResult.CONTROL_AE_STATE)
            if (aeState == null || aeState == CaptureResult.CONTROL_AE_STATE_CONVERGED) {
                state = STATE_PICTURE_TAKEN
                captureStillPicture()
            } else {
                runPrecaptureSequence()
            }
        }
        null -> captureStillPicture()
        else -> restartFocus()
    }
}
```

Step 2 - Add `restartFocus()`

```kotlin
private fun restartFocus() {
    try {
        previewRequestBuilder.set(CaptureRequest.CONTROL_AF_TRIGGER, CameraMetadata.CONTROL_AF_TRIGGER_CANCEL)
        captureSession?.capture(previewRequestBuilder.build(), captureCallback, backgroundHandler)
        lockFocus()
    } catch (e: CameraAccessException) {
        Log.e(CameraFragment::class.java.simpleName, e.toString())
    }
}
```

Step 3 - Add Delay for `repeatingRequest` inside `unlockFocus()`

```kotlin
private fun unlockFocus() {
    try {
        // Reset the auto-focus trigger
        previewRequestBuilder.set(CaptureRequest.CONTROL_AF_TRIGGER, CameraMetadata.CONTROL_AF_TRIGGER_CANCEL)
        captureSession?.capture(previewRequestBuilder.build(), captureCallback, backgroundHandler)
        // After this, the camera will go back to the normal state of preview.
        state = STATE_PREVIEW
        Handler().postDelayed({
            captureSession?.setRepeatingRequest(previewRequest, captureCallback, backgroundHandler)
        }, 500)
    } catch (e: CameraAccessException) {
        Log.e(CameraFragment::class.java.simpleName, e.toString())
    }
}
```
Special thanks to these StackOverFlow discussion that enabled me to figure it out.

https://stackoverflow.com/questions/44527420/android-camera2-focus-state-stuck

https://stackoverflow.com/questions/40146485/session-has-been-closed-further-changes-are-illegal

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
