### ISSUE TITLE
Can this use watermark or photo in camera?

### ISSUE THREAD

**Issue by lowfiend** [googlesamples/android-Camera2Basic#35]
I want to add sample background and than users use it to take a photo

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
