### ISSUE TITLE
Incorrect aspect ratio after going to landscape mode then back to portrait

### ISSUE THREAD

**Issue by svofski** [googlesamples/android-Camera2Basic#38]
Nexus 7 5.0 LPX13D 
App starts up fine, after turning to landscape it recreates the activity ok, after turning back to portrait the sensor orientation does not match display orientation and swappedDimensions is true. The result is distorted/skewed preview display.

**Comment by RoundSparrow** [comment]
Is this possibly a repeat of Issue #9

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
