### ISSUE TITLE
Camera image upside down after orientation changes

### ISSUE THREAD

**Issue by schildbach** [googlesamples/android-Camera2Basic#43]
If changing from one landscape orientation to the other very fast, such that it doesn't switch to portrait inbetween, the camera image is upside down afterwards. This is on a Nexus 4 updated to Android 5.1.

**Comment by RoundSparrow** [comment]
There is a Pull request you might want to try: https://github.com/googlesamples/android-Camera2Basic/pull/27

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
