### ISSUE TITLE
Source code "CameraCaptureSession.CaptureCallback CaptureCallback" camelCase

### ISSUE THREAD

**Issue by RoundSparrow** [googlesamples/android-Camera2Basic#45]
The variable starts with an uppercase letter "Capture".

Also of note: The comment for the method "This method should be called when we get a response in
     \* {@link #mCaptureCallback} from both {@link #lockFocus()}" seems incomplete.  It implies "from both" in English language - but only lists a single item.  As a tutorial/sample app, would be better to make sure that something isn't missing in this comment.

Thank you.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
