### ISSUE TITLE
Taking snapshots while screen is off

### ISSUE THREAD

**Issue by RonyDimebag** [googlesamples/android-Camera2Basic#47]
Hi, this is not exactly an issue, since I don't know if this is a desired behavior.

I played a bit with the code and everything works great, the only thing I can't achieve is taking snapshots from the camera while the screen is off (imagine a smartphone working as a motion detector 24/7, I don't want to keep the screen on all the time).

When the screen is locked all the surface objects are dismissed and I can't find a way to keep taking timed snapshots.

Is there any advice on how to achieve this?
Thank you

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
