### ISSUE TITLE
Camera2 Support below Api level 21

### ISSUE THREAD

**Issue by dharmeshmp** [googlesamples/android-Camera2Basic#49]
Hi
is there any way to support camera2 below api level 21

**Comment by filipebezerra** [comment]
No, even though the old camera API is marked as deprecated, it is still fully functional, and will remain so for quite a while (as nearly all camera-using applications on the Play Store use it currently)

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
