### ISSUE TITLE
Turn portrait mode 180 degrees preview is upside down

### ISSUE THREAD

**Issue by jingxizhang** [googlesamples/android-Camera2Basic#5]
Turn portrait mode 180 degrees then the preview is upside down.

**Comment by github-tn** [comment]
how to rotate the preview 90 degree?

**Comment by github-tn** [comment]
how to rotate the camera preview? 

![image](http://i57.tinypic.com/rh3jg0.png)

**Comment by yaraki** [comment]
What device are you using?
At least for Nexus 9, the preview is working fine in the opposite portrait.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
