### ISSUE TITLE
error RenderThread in camera

### ISSUE THREAD

**Issue by huyquyet** [googlesamples/android-Camera2Basic#50]
06-30 13:58:55.991 30542-30542/? A/DEBUG: pid: 9082, tid: 9349, name: RenderThread  >>> com.myproject<<<

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
