### ISSUE TITLE
How to open front camera

### ISSUE THREAD

**Issue by parthivikky** [googlesamples/android-Camera2Basic#51]
Hi, My application requirements is,  I want to open front camera and take selfie. What should i do to open front camera. Is it possible?

**Comment by AlejandroHCruz** [comment]
It's possible, take a look at this: http://stackoverflow.com/a/33779582/4657995

**Comment by alu0100207385** [comment]
Update: https://stackoverflow.com/questions/39022845/android-camera2-api-switch-back-front-cameras#answer-48680929

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
