### ISSUE TITLE
Camera layout is skewed after being resumed from lock screen?

### ISSUE THREAD

**Issue by FavoRiteKK** [googlesamples/android-Camera2Basic#52]
I changed this app to landscape orientation only.

And it works just fine if I press home and then open the app again, it resumes properly. But if I press the power button, then I turn my device on, and resume to the app, there is the error: "An error occurred while connecting to camera: 0", and the app just closes afterward.

So, I added android:configChanges with value "orientation|screenSize" and now the above error doesn't happen, but the screen layout is skewed.
[screenshot](http://i.stack.imgur.com/2zG8G.png)
I don't understand, what is the difference between the two cases: pressing the power button off versue pressing the home button?

**Comment by KnYaZuK** [comment]
Change the following code
`if (orientation == Configuration.ORIENTATION_LANDSCAPE) {
                    mTextureView.setAspectRatio(
                            mPreviewSize.getWidth(), mPreviewSize.getHeight());
                } else {
                    mTextureView.setAspectRatio(
                            mPreviewSize.getHeight(), mPreviewSize.getWidth());
                }`
to this
`mTextureView.setAspectRatio(mPreviewSize.getWidth(), mPreviewSize.getHeight());`

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
