### ISSUE TITLE
Not capturing picture (ViewPostImeInputStage ACTION_DOWN) - Galaxy Tab4 10.1 3G

### ISSUE THREAD

**Issue by mobinius-prem** [googlesamples/android-Camera2Basic#58]
The sample code not captures the photo but preview stays still.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
