### ISSUE TITLE
how to pause preview?

### ISSUE THREAD

**Issue by wanghao225225** [googlesamples/android-Camera2Basic#59]
Hi,
   My question is: How to pause the preview( and draw some figures on the screen), and( touch a button to) resume previewing?

Thank you!

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
