### ISSUE TITLE
Front Camera

### ISSUE THREAD

**Issue by EMIN3M1986** [googlesamples/android-Camera2Basic#60]
Hi.
When I'm using front camera it dose not take a picture and log shows this:

```
 W/LegacyRequestMapper: convertRequestMetadata - control.awbRegions setting is not supported, ignoring value
 W/LegacyMetadataMapper: convertAfModeToLegacy - ignoring unsupported mode 4, defaulting to fixed
 W/LegacyRequestMapper: convertRequestMetadata - control.awbRegions setting is not supported, ignoring value
 W/LegacyMetadataMapper: convertAfModeToLegacy - ignoring unsupported mode 4, defaulting to fixed
```

I have this problem with Samsung Galaxy Note 4, But on Samsung Galaxy S4 everything are well;
Both have android 6 (Marshmallow).

**Comment by fabcam** [comment]
@EMIN3M1986 hey, any hints on this issue??

**Comment by more207** [comment]
In lockFocus() method, replace line
mCaptureSession.capture(mPreviewRequestBuilder.build(), mCaptureCallback, mBackgroundHandler);
with
captureStillPicture();

by
https://stackoverflow.com/questions/33127258/front-camera-in-camera2-not-capturing-image

**Comment by fabcam** [comment]
Thanks for your answer! The problem was that front camera didn't support Auto Focus (took me some time to realize that that was the real issue) and ended up doing what you suggested.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
