### ISSUE TITLE
java.lang.RuntimeException: Unable to start activity ComponentInfo ~ android.view.InflateException: Binary XML file line #6: Binary XML file line #6: Error inflating class com.example.android.camera2basic.AutoFitTextureView

### ISSUE THREAD

**Issue by kogisin** [googlesamples/android-Camera2Basic#63]
I basically copied and pasted all the code that is provided in my Samsung Galaxy Note 5, 
and i get the following error.

"java.lang.RuntimeException: Unable to start activity ComponentInfo ~ android.view.InflateException: Binary XML file line #6: Binary XML file line #6: Error inflating class com.example.android.camera2basic.AutoFitTextureView"

Do you have any idea how to fix it? i have been searching all day...

**Comment by Sumsar** [comment]
Check that the AutoFitTextureView tag in camera fragment xml is correct

**Comment by takharvinod** [comment]
use in your fragment     class="com.horya.Activities.UserNavigationDrawerFragment" to change android="com.horya.activity..................."
i fix this error.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
