### ISSUE TITLE
Full screen preview

### ISSUE THREAD

**Issue by Carpetfizz** [googlesamples/android-Camera2Basic#66]
Hello,

I removed the `@+id/control` `<FrameLayout/>` containing the "Picture" button and "Info" button. I want the preview to stretch full screen but there is still a black bar left at the bottom where the `<FrameLayout/>` used to be. I've set the layout to `match_parent` on both fragment layouts to no effect.

Thanks.

**Comment by Raniazy** [comment]
Hello @Carpetfizz 
After removing ```@+id/control```   ```<FrameLayout/>``` 
Try editing ```@+id/texture```  ```AutoFitTextureView``` 
- from ```android:layout_width="wrap_content"``` to ```android:layout_width="match_parent"```
- from ```android:layout_height="wrap_content"``` to  ```android:layout_height="match_parent"```

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
