### ISSUE TITLE
Side bar crashes when rotating to landscape

### ISSUE THREAD

**Issue by drbugfinder** [googlesamples/android-Camera2Basic#67]
Hi,
every time I set the device to landscape, the menu bar crashes but comes back after I rotate it into portrait.
See stack trace below:
`01-27 11:26:44.123 27412-27530/com.example.android.camera2basic I/OpenGLRenderer: Initialized EGL, version 1.4
01-27 11:26:44.163 27412-27412/com.example.android.camera2basic I/CameraManagerGlobal: Connecting to camera service
01-27 11:26:44.213 27412-27418/com.example.android.camera2basic W/art: Suspending all threads took: 14.781ms
01-27 11:26:44.223 27412-27412/com.example.android.camera2basic I/CameraManager: Using legacy camera HAL.
01-27 11:26:44.603 27412-27530/com.example.android.camera2basic D/libGLESv1: DTS_GLAPI : DTS is not allowed for Package : com.example.android.camera2basic
01-27 11:26:44.613 27412-27527/com.example.android.camera2basic I/CameraDeviceState: Legacy camera service transitioning to state CONFIGURING
01-27 11:26:44.623 27412-27630/com.example.android.camera2basic I/RequestThread-0: Configure outputs: 2 surfaces configured.
01-27 11:26:44.623 27412-27630/com.example.android.camera2basic D/Camera: app passed NULL surface
01-27 11:26:44.633 27412-27630/com.example.android.camera2basic I/RequestThread-0: configureOutputs - set take picture size to 2592x1944
01-27 11:26:44.763 27412-27527/com.example.android.camera2basic I/CameraDeviceState: Legacy camera service transitioning to state IDLE
01-27 11:26:44.773 27412-27527/com.example.android.camera2basic I/RequestQueue: Repeating capture request set.
01-27 11:26:44.783 27412-27630/com.example.android.camera2basic W/LegacyRequestMapper: convertRequestMetadata - control.awbRegions setting is not supported, ignoring value
01-27 11:26:44.783 27412-27630/com.example.android.camera2basic W/LegacyRequestMapper: Only received metering rectangles with weight 0.
01-27 11:26:44.783 27412-27630/com.example.android.camera2basic W/LegacyRequestMapper: Only received metering rectangles with weight 0.
01-27 11:26:44.793 27412-27412/com.example.android.camera2basic D/ViewRootImpl: MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
01-27 11:26:44.813 27412-27412/com.example.android.camera2basic I/Choreographer: Skipped 38 frames!  The application may be doing too much work on its main thread.
01-27 11:26:44.823 27412-27412/com.example.android.camera2basic I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@df54701 time:80214286
01-27 11:26:45.433 27412-27641/com.example.android.camera2basic I/CameraDeviceState: Legacy camera service transitioning to state CAPTURING
01-27 11:27:12.253 27412-27422/com.example.android.camera2basic I/art: Background sticky concurrent mark sweep GC freed 478165(15MB) AllocSpace objects, 0(0B) LOS objects, 82% free, 3MB/18MB, paused 1.124ms total 116.333ms
01-27 11:27:39.083 27412-27422/com.example.android.camera2basic I/art: Background sticky concurrent mark sweep GC freed 477121(14MB) AllocSpace objects, 0(0B) LOS objects, 80% free, 3MB/18MB, paused 1.064ms total 111.007ms
01-27 11:28:05.133 27412-27418/com.example.android.camera2basic W/art: Suspending all threads took: 52.263ms
01-27 11:28:05.143 27412-27422/com.example.android.camera2basic I/art: Background sticky concurrent mark sweep GC freed 462830(14MB) AllocSpace objects, 0(0B) LOS objects, 77% free, 4MB/18MB, paused 1.410ms total 118.149ms
01-27 11:28:30.423 27412-27422/com.example.android.camera2basic I/art: Background sticky concurrent mark sweep GC freed 448666(13MB) AllocSpace objects, 0(0B) LOS objects, 75% free, 4MB/18MB, paused 1.239ms total 110.589ms
                                                                       
                                                                       [ 01-27 11:28:30.423   365:27665 E/         ]
                                                                       af_process_parse_stats: Invalid FV data!
                                                                       
                                                                       [ 01-27 11:28:30.423   365:27665 E/         ]
                                                                       af_process_1: Error processing AF stats!
01-27 11:28:35.933 27412-27412/com.example.android.camera2basic I/RequestQueue: Repeating capture request cancelled.
01-27 11:28:35.993 27412-27423/com.example.android.camera2basic E/BufferQueueProducer: [SurfaceTexture-1-27412-1] queueBuffer: BufferQueue has been abandoned
01-27 11:28:35.993 27412-27424/com.example.android.camera2basic E/BufferQueueProducer: [SurfaceTexture-1-27412-1] dequeueBuffer: BufferQueue has been abandoned
01-27 11:28:36.013 27412-27743/com.example.android.camera2basic E/BufferQueueProducer: [SurfaceTexture-1-27412-1] cancelBuffer: BufferQueue has been abandoned
01-27 11:28:36.013 27412-27423/com.example.android.camera2basic E/BufferQueueProducer: [SurfaceTexture-1-27412-1] cancelBuffer: BufferQueue has been abandoned
01-27 11:28:36.013 27412-27424/com.example.android.camera2basic E/BufferQueueProducer: [SurfaceTexture-1-27412-1] cancelBuffer: BufferQueue has been abandoned
01-27 11:28:36.013 27412-27743/com.example.android.camera2basic E/BufferQueueProducer: [SurfaceTexture-1-27412-1] cancelBuffer: BufferQueue has been abandoned
01-27 11:28:36.013 27412-27423/com.example.android.camera2basic E/BufferQueueProducer: [SurfaceTexture-1-27412-1] cancelBuffer: BufferQueue has been abandoned
01-27 11:28:36.013 27412-27424/com.example.android.camera2basic E/BufferQueueProducer: [SurfaceTexture-1-27412-1] cancelBuffer: BufferQueue has been abandoned
01-27 11:28:36.263 27412-27412/com.example.android.camera2basic D/ViewRootImpl: #3 mView = null
01-27 11:28:36.313 27412-27412/com.example.android.camera2basic D/SecWifiDisplayUtil: Metadata value : SecSettings2
01-27 11:28:36.313 27412-27412/com.example.android.camera2basic D/ViewRootImpl: #1 mView = com.android.internal.policy.PhoneWindow$DecorView{f26f145 I.E...... R.....ID 0,0-0,0}
01-27 11:28:36.343 27412-27412/com.example.android.camera2basic E/ViewRootImpl: sendUserActionEvent() mView == null
01-27 11:28:36.363 27412-27412/com.example.android.camera2basic I/CameraManager: Using legacy camera HAL.
01-27 11:28:36.703 27412-29267/com.example.android.camera2basic I/CameraDeviceState: Legacy camera service transitioning to state CONFIGURING
01-27 11:28:36.713 27412-29304/com.example.android.camera2basic I/RequestThread-0: Configure outputs: 2 surfaces configured.
01-27 11:28:36.713 27412-27412/com.example.android.camera2basic D/ViewRootImpl: MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=2
01-27 11:28:36.713 27412-29304/com.example.android.camera2basic D/Camera: app passed NULL surface
01-27 11:28:36.723 27412-27412/com.example.android.camera2basic I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@df54701 time:80326189
01-27 11:28:36.733 27412-29304/com.example.android.camera2basic I/RequestThread-0: configureOutputs - set take picture size to 2592x1944
01-27 11:28:36.763 27412-29267/com.example.android.camera2basic I/CameraDeviceState: Legacy camera service transitioning to state IDLE
01-27 11:28:36.763 27412-29267/com.example.android.camera2basic I/RequestQueue: Repeating capture request set.
01-27 11:28:36.773 27412-29304/com.example.android.camera2basic W/LegacyRequestMapper: convertRequestMetadata - control.awbRegions setting is not supported, ignoring value
01-27 11:28:36.773 27412-29304/com.example.android.camera2basic W/LegacyRequestMapper: Only received metering rectangles with weight 0.
01-27 11:28:36.773 27412-29304/com.example.android.camera2basic W/LegacyRequestMapper: Only received metering rectangles with weight 0.
01-27 11:28:37.143 27412-29306/com.example.android.camera2basic I/CameraDeviceState: Legacy camera service transitioning to state CAPTURING
01-27 11:28:38.203 27412-27412/com.example.android.camera2basic I/RequestQueue: Repeating capture request cancelled.
01-27 11:28:38.213 27412-27424/com.example.android.camera2basic W/MessageQueue: Handler (android.graphics.SurfaceTexture$1) {4f27854} sending message to a Handler on a dead thread
                                                                                java.lang.IllegalStateException: Handler (android.graphics.SurfaceTexture$1) {4f27854} sending message to a Handler on a dead thread
                                                                                    at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
                                                                                    at android.os.Handler.enqueueMessage(Handler.java:631)
                                                                                    at android.os.Handler.sendMessageAtTime(Handler.java:600)
                                                                                    at android.os.Handler.sendMessageDelayed(Handler.java:570)
                                                                                    at android.os.Handler.sendEmptyMessageDelayed(Handler.java:534)
                                                                                    at android.os.Handler.sendEmptyMessage(Handler.java:519)
                                                                                    at android.graphics.SurfaceTexture.postEventFromNative(SurfaceTexture.java:376)
01-27 11:28:38.243 27412-27423/com.example.android.camera2basic E/BufferQueueProducer: [SurfaceTexture-1-27412-3] queueBuffer: BufferQueue has been abandoned
01-27 11:28:38.243 27412-27424/com.example.android.camera2basic E/BufferQueueProducer: [SurfaceTexture-1-27412-3] dequeueBuffer: BufferQueue has been abandoned
01-27 11:28:38.273 27412-27743/com.example.android.camera2basic E/BufferQueueProducer: [SurfaceTexture-1-27412-3] queueBuffer: BufferQueue has been abandoned
01-27 11:28:38.283 27412-27423/com.example.android.camera2basic E/BufferQueueProducer: [SurfaceTexture-1-27412-3] dequeueBuffer: BufferQueue has been abandoned
01-27 11:28:38.313 27412-27424/com.example.android.camera2basic E/BufferQueueProducer: [SurfaceTexture-1-27412-3] cancelBuffer: BufferQueue has been abandoned
01-27 11:28:38.313 27412-27743/com.example.android.camera2basic E/BufferQueueProducer: [SurfaceTexture-1-27412-3] cancelBuffer: BufferQueue has been abandoned
01-27 11:28:38.313 27412-27423/com.example.android.camera2basic E/BufferQueueProducer: [SurfaceTexture-1-27412-3] cancelBuffer: BufferQueue has been abandoned
01-27 11:28:38.313 27412-27424/com.example.android.camera2basic E/BufferQueueProducer: [SurfaceTexture-1-27412-3] cancelBuffer: BufferQueue has been abandoned
01-27 11:28:38.323 27412-27743/com.example.android.camera2basic E/BufferQueueProducer: [SurfaceTexture-1-27412-3] cancelBuffer: BufferQueue has been abandoned
01-27 11:28:38.323 27412-27423/com.example.android.camera2basic E/BufferQueueProducer: [SurfaceTexture-1-27412-3] cancelBuffer: BufferQueue has been abandoned
01-27 11:28:38.553 27412-27412/com.example.android.camera2basic D/ViewRootImpl: #3 mView = null
01-27 11:28:38.593 27412-27412/com.example.android.camera2basic D/SecWifiDisplayUtil: Metadata value : SecSettings2
01-27 11:28:38.593 27412-27412/com.example.android.camera2basic D/ViewRootImpl: #1 mView = com.android.internal.policy.PhoneWindow$DecorView{9ce9e84 I.E...... R.....ID 0,0-0,0}
01-27 11:28:38.633 27412-27412/com.example.android.camera2basic E/ViewRootImpl: sendUserActionEvent() mView == null
01-27 11:28:38.653 27412-27412/com.example.android.camera2basic I/CameraManager: Using legacy camera HAL.
01-27 11:28:38.993 27412-29359/com.example.android.camera2basic I/CameraDeviceState: Legacy camera service transitioning to state CONFIGURING
01-27 11:28:38.993 27412-29396/com.example.android.camera2basic I/RequestThread-0: Configure outputs: 2 surfaces configured.
01-27 11:28:38.993 27412-27412/com.example.android.camera2basic D/ViewRootImpl: MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
01-27 11:28:39.003 27412-29396/com.example.android.camera2basic D/Camera: app passed NULL surface
01-27 11:28:39.013 27412-29396/com.example.android.camera2basic I/RequestThread-0: configureOutputs - set take picture size to 2592x1944
01-27 11:28:39.013 27412-27412/com.example.android.camera2basic I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@df54701 time:80328478
01-27 11:28:39.043 27412-29359/com.example.android.camera2basic I/CameraDeviceState: Legacy camera service transitioning to state IDLE
01-27 11:28:39.043 27412-29359/com.example.android.camera2basic I/RequestQueue: Repeating capture request set.`

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
