### ISSUE TITLE
How to increase captured image quality?

### ISSUE THREAD

**Issue by DmitriiSemeniuc** [googlesamples/android-Camera2Basic#68]
There is a difference of image quality between camera preview and saved image. How to capture an image without loosing of quality? My full explained question: http://stackoverflow.com/questions/41910730/how-to-increase-camera-2-image-quality-in-android . Tested on Samsung Note 5.

**Comment by limitlessisa** [comment]
Samsung s7 edge; same problem.

![screenshot_20170623-130306](https://user-images.githubusercontent.com/12773794/27480094-50b69404-581f-11e7-9a33-fce14368c9c2.jpg)

**Comment by IamSantosh** [comment]
I'm also facing this problem. There's a huge difference between size of the image on captured from Image App and Camera 2 API. 
If you get any solution, then can you please also help me.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
