### ISSUE TITLE
Different aspect ratio on different devices

### ISSUE THREAD

**Issue by carlognegna** [googlesamples/android-Camera2Basic#69]
List of devices:
- Vodafone VF895N
- Huawei Ascend P7
- HTC One M8 

Camera aspect ratio is totally different comparing all these device, the only once correct seems on Huawei

On HTC you can see a vertical black bar on right
![htc one_m8](https://cloud.githubusercontent.com/assets/25816142/23016718/c472bbc6-f437-11e6-95e0-4e7154f64acb.png)

Here seems fine
![huawei ascend p7](https://cloud.githubusercontent.com/assets/25816142/23016747/e38efd58-f437-11e6-8b9a-c0521c9b3734.png)

On VF895N image is totally distorted
![vodafone vf895n](https://cloud.githubusercontent.com/assets/25816142/23016759/f0d5396e-f437-11e6-8c31-322e163706fb.png)

**Comment by wkmeijer** [comment]
Take a look at[ this solution](https://stackoverflow.com/a/41222110), this worked for me.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
