### ISSUE TITLE
App fails to open 

### ISSUE THREAD

**Issue by yrizk** [googlesamples/android-Camera2Basic#7]
E/AndroidRuntime( 5504): FATAL EXCEPTION: main
E/AndroidRuntime( 5504): Process: com.yohan.cameraexample, PID: 5504
E/AndroidRuntime( 5504): java.lang.RuntimeException: setParameters failed
E/AndroidRuntime( 5504):    at android.hardware.Camera.native_setParameters(Native Method)
E/AndroidRuntime( 5504):    at android.hardware.Camera.setParameters(Camera.java:1876)
E/AndroidRuntime( 5504):    at com.yohan.cameraexample.Preview.surfaceChanged(Preview.java:77)
E/AndroidRuntime( 5504):    at android.view.SurfaceView.updateWindow(SurfaceView.java:590)
E/AndroidRuntime( 5504):    at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:176)
E/AndroidRuntime( 5504):    at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:847)
E/AndroidRuntime( 5504):    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1956)
E/AndroidRuntime( 5504):    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1054)
E/AndroidRuntime( 5504):    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5779)
E/AndroidRuntime( 5504):    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
E/AndroidRuntime( 5504):    at android.view.Choreographer.doCallbacks(Choreographer.java:580)
E/AndroidRuntime( 5504):    at android.view.Choreographer.doFrame(Choreographer.java:550)
E/AndroidRuntime( 5504):    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
E/AndroidRuntime( 5504):    at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime( 5504):    at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 5504):    at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 5504):    at android.app.ActivityThread.main(ActivityThread.java:5221)
E/AndroidRuntime( 5504):    at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 5504):    at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 5504):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
E/AndroidRuntime( 5504):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by mobidroid** [comment]
any luck in identifying this issue?

**Comment by yrizk** [comment]
Unfortunately, no I didn't have the time to figure it out. Short of not using `setParameters()` that is

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
