### ISSUE TITLE
Crash when starting - NoClassDefFoundError

### ISSUE THREAD

**Issue by DanieBeets** [googlesamples/android-Camera2Basic#70]
I am running this app on a device which does not have a "camera app".

The following error occurs in the OnCreate() method of Camera2BasicFragment.cs when instantiating an object of type CameraStateListener().

Java.Lang.NoClassDefFoundError: md5e43eb8ca6ea16e1d9c5a1b38539fbc13/CameraStateListener

I am not too sure that this is a problem with my device or with the code, but any help will be appreciated.

**Comment by DanieBeets** [comment]
Works fine on an LG G3.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
