### ISSUE TITLE
Gradle wrapper out of date

### ISSUE THREAD

**Issue by Kyle-Falconer** [googlesamples/android-Camera2Basic#73]
The Gradle version in this project is 2.2.3.

Latest is version is 2.3.0

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
