### ISSUE TITLE
missing .gitignore file

### ISSUE THREAD

**Issue by Kyle-Falconer** [googlesamples/android-Camera2Basic#76]
The missing `.gitignore` file makes contributing to this repository a messy affair. The gitignore should ignore generated files by Gradle and Android Studio.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
