### ISSUE TITLE
OnImageAvailable never called 

### ISSUE THREAD

**Issue by mnive93** [googlesamples/android-Camera2Basic#78]
After unlocking focus OnImageAvailable listener is never called sometimes . After I capture some 50 - 60 images, Repeating request is stopped and cleared.

**Comment by ygModesto** [comment]
On MIUI devices onImageAvailable is never called.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
