### ISSUE TITLE
Camera scaled on font camera of Nexus 7 2013

### ISSUE THREAD

**Issue by FrankNT** [googlesamples/android-Camera2Basic#8]
When I change the code for Front Camera

```
            if (characteristics.get(CameraCharacteristics.LENS_FACING)
                    == CameraCharacteristics.LENS_FACING_FRONT) {
```

//                    continue;  // Coment here
//                }  // Coment here

..... do some thing here

////

Some time the display screen is scaled, some time it works. When I stop and resume application, it works perfect.

What's did I do wrong and how to fix it?

![screen shot 2015-04-10 at 2 58 07 pm](https://cloud.githubusercontent.com/assets/5534157/7083964/201c4256-df92-11e4-86a9-bb8121efa40a.png)

**Comment by CJZwork** [comment]
I have the same problem, do you fix it ? Please tell me if you do.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
