### ISSUE TITLE
Pixel C front camera - portrait issue

### ISSUE THREAD

**Issue by VladOstrovski** [googlesamples/android-Camera2Basic#81]
When trying to use the front camera instead of back, with Pixel C on Portrait, the preview's aspect ratio is wrong and it doesn't scale to the view's size correctly.
![device-2017-05-29-111941](https://cloud.githubusercontent.com/assets/18282436/26542006/e915ebf0-4460-11e7-8655-4202168accc8.png)

**Comment by VladOstrovski** [comment]
Fixing the stretch can be done by caching the swappedDimensions boolean and replacing line 750 with
`        RectF bufferRect = new RectF();
        if (mSwappedDimensions){
            bufferRect.set(0, 0, mPreviewSize.getWidth(), mPreviewSize.getHeight());
        }else{
            bufferRect.set(0, 0, mPreviewSize.getHeight(), mPreviewSize.getWidth());
        }`

But the preview still anchors to the left.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
