### ISSUE TITLE
Please add a description to this repo

### ISSUE THREAD

**Issue by dandv** [googlesamples/android-Camera2Basic#84]
![image](https://user-images.githubusercontent.com/33569/27246899-aa58dd12-52a9-11e7-9251-979017fe38d2.png)

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
