### ISSUE TITLE
Why FPS down when I get byte[] from Image?

### ISSUE THREAD

**Issue by hirorogithub** [googlesamples/android-Camera2Basic#85]
I want to get every preview frame from camera to do some cv algrithm.But when i just got bytes from image(which I get from the imageReader.onImageAccessable),FPS become lower than camera api1 under the same resolution.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
