### ISSUE TITLE
IllegalStateException: maxImages (2) has already been acquired, call #close before acquiring more.

### ISSUE THREAD

**Issue by agilangovan** [googlesamples/android-Camera2Basic#86]
I get an illegalStateException after I take 2 pictures. This has been happening with the OnePlus3 phone. I looked online and found out that I am supposed to close the Image object. But I do not know where to close this image. Where do I close it?

**Comment by yudikarma** [comment]
@Override
        public void onImageAvailable(ImageReader reader) {
            try {

                    if (haslocation){
                    File dir = new File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DCIM), "Image Project");
                    if (!dir.exists())
                        dir.mkdir();

                    file = new File(dir, currentDate + ".jpg");
                    Image image = reader.acquireNextImage();
                    ByteBuffer buffer = image.getPlanes()[0].getBuffer();
                    byte[] bytes = new byte[buffer.remaining()];
                    buffer.get(bytes);


                    try {
                        saveMetaData(file);
                    } catch (IOException e) {
                        e.printStackTrace();
                    }


                    saveImageFile(bytes);
                    /*mBackgroundHandler.post(new ImageSaver(reader.acquireLatestImage(),file));*/


                    //close image to fix crash second time capture
                    image.close();

                }else {
                        Toast.makeText(ShotActivity_camera2API.this,"location null",Toast.LENGTH_SHORT).show();
                    }
            } catch (Exception e) {
                e.printStackTrace();
            } /*catch (IOException e) {
                e.printStackTrace();
            }*/
        }

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
