### ISSUE TITLE
App is not working on Nexus 6

### ISSUE THREAD

**Issue by ankitac862** [googlesamples/android-Camera2Basic#87]
When an app is installed in Nexus 6 device, UI components are loaded but the camera is not displayed. 
After few sec app shut down without any error message. 

08-01 16:13:41.656 9475-9502/com.example.android.camera2basic I/OpenGLRenderer: Initialized EGL, version 1.4
08-01 16:13:41.698 9475-9475/com.example.android.camera2basic I/CameraManagerGlobal: Connecting to camera service
08-01 16:13:52.852 9475-9475/com.example.android.camera2basic E/BufferQueueProducer: [SurfaceTexture-0-9475-0] connect(P): already connected (cur=4 req=4)
08-01 16:13:53.258 9475-9475/com.example.android.camera2basic W/CameraDevice-JV-0: Stream configuration failed
08-01 16:13:53.259 9475-9475/com.example.android.camera2basic E/CameraCaptureSession: Session 0: Failed to create capture session; configuration failed

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
