### ISSUE TITLE
Picture not taken - sample should check whether the camera device supports auto-focus

### ISSUE THREAD

**Issue by jasonwedepohl** [googlesamples/android-Camera2Basic#88]
Some cameras do not support auto-focus (for instance, the front-facing camera of the device I'm using). In the sample app, this results in the app failing to take a photo.

I found this same question being asked by several different people on here and on StackOverflow, and people have been asking this question over the past couple of years. An update to the sample app is long overdue.

I found a promising answer [here](https://stackoverflow.com/questions/33127258/front-camera-in-camera2-not-capturing-image/40597153#40597153). in takePicture(), the app should call captureStillImage rather than lockFocus if auto-focus is not supported by the selected camera.

Technical info: The Capture callback "process()" method does not have a condition branch for the case where the autofocus algorithm is inactive (i.e. where afState = 0). Consequently if the selected camera device does not support autofocus, stillImageCapture() never gets called.

**Comment by WillWolfWang** [comment]
你说的是正确的，我的设备执行lockFocus()这个方法，就没有任何反应，日志信息也没有输出相关的内容，你的方法解决了我的问题。thank you

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
