### ISSUE TITLE
Preview display skewed

### ISSUE THREAD

**Issue by JohnGoertz** [googlesamples/android-Camera2Basic#9]
Sometimes the preview presents a skewed image, as if you were elongating the image. Here's the most consistent way I can reproduce this:

1) Start the app with phone in portrait mode. Preview may or may not be fine. If it is fine:
2) Rotate the phone to landscape. Preview should stay fine.
3) Rotate back to portrait. Now the preview should be weird and skewed.

I know that's a confusing description, hopefully you can reproduce it. I'm guessing it has to do with the configureTransform method?

**Comment by jasontsitsaris** [comment]
I have the same exactly problem using front camera.
When you enter the app image is weirdly stretched.
If you exit and reenter the app then camera just works fine.

**Comment by yaraki** [comment]
What device are you using?

**Comment by jasontsitsaris** [comment]
I am using a Sony Xperia Z1.
I was also forced to comment code for autofocus because the app was crushing. 
I was trying to understand what was different in onStop() and onResume() methods but I didn't worked it out.

**Comment by JohnGoertz** [comment]
I'm using a HTC One m7 running CyanogenMod 12.0.

**Comment by ishit** [comment]
I am using Moto G (XT1033). The preview is skewed as show below with the start of the activity. On resuming the activity, the preview turns back to normal. 
![device-2015-06-23-210636](https://cloud.githubusercontent.com/assets/4801132/8310185/e88f5ca8-19eb-11e5-8e84-172abb50125a.png)
![device-2015-06-23-210535](https://cloud.githubusercontent.com/assets/4801132/8310184/e88c6a20-19eb-11e5-80f8-c6e54fcfa84d.png)

**Comment by CJZwork** [comment]
Hey guys, do you fix thie problem ? I got the same problem.
When the preview is skewed, I just turned the screen off and turn back on again and the preview is fine now.

**Comment by mlu42** [comment]
Same here. It also gives me an error 
"E/BufferQueueProducer﹕ [unnamed-26081-14] dequeueBuffer: min undequeued buffer count (2) exceeded (dequeued=6 undequeued=1)" 
followed by 
"E/BufferQueueProducer﹕ [unnamed-26081-14] dequeueBuffer: BufferQueue has been abandoned"

Any idea how to fix this?

**Comment by HaakonBj** [comment]
Had the same problem. Fixed by hiding the bars ontop.

**Comment by mlu42** [comment]
Bars on top? You meant the action bar?

**Comment by HaakonBj** [comment]
Yea the Bar that says Camera2 with the back button and the bar with the battery and all that.

**Comment by vgrec** [comment]
Anyone found a solution for the preview distortion problem?

**Comment by DimalPerera** [comment]
Any solution for this issue ??

**Comment by PoloShock** [comment]
For anyone struggling with this issue check my workaround at https://stackoverflow.com/a/48138680/937678

**Comment by rameshbabudevalingam** [comment]
Any working solutions for this issue?

**Comment by GuanacoDevs** [comment]
I had the same issue with a LG Phone, solved it setting this on my TextureView Layout:
```
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
```

**Comment by rameshbabudevalingam** [comment]
@GuanacoDevs thanks but that didn't help..

**Comment by damaro333** [comment]
I am also having this problem with my Galaxy Tab A 10.1" - 1920x1200 is the original solution. TextureView Ratio and size is set to 1920:1080 because I need 16:9 pictures and because the camera has no full screen functionality. The delay before opening also does not help.

Any other ideas @PoloShock ?

**Comment by PoloShock** [comment]
@damaro333 if the delay didn't help, I have no other thoughts, sorry. :(

**Comment by damaro333** [comment]
@PoloShock I was able to solve this issue with setting the ratio to 4:3. I did not have the problem with few 16:9 mobiles like the Galaxy J5, with the Galaxy Note 8 which is 18,5x9 ...Only with the Galaxy Tab A 10.1...the display is 16:10 and it seems to be a hardware issue. 

So no hard feelings about it, will try it in a few months.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
