### ISSUE TITLE
front camera takes pic upside down

### ISSUE THREAD

**Issue by GunaseelanArumaikkannu** [googlesamples/android-Camera2Basic#90]
I have tried this sample app. For front camera get works I have changed some code in Camera2BasicFragment. The changes are as follows.

To Switch to front camera I have changed mCameraId = cameraId; to mCameraId = "1"; in setUpCameraOutputs(int width, int height) method.

This change shows front camera perfectly but doesn't pick the photo. So I replaced

mCaptureSession.capture(mPreviewRequestBuilder.build(), mCaptureCallback,
                        mBackgroundHandler);
to

captureStillPicture();
in lockFocus(). Now front camera picks the photo, but it looks upside down.

for ex:
![pic](https://user-images.githubusercontent.com/4026883/29925529-2daec5d6-8e7e-11e7-9d5b-4b3377874c67.jpg)
I don't know what to do now?
Actually my requirement is to capture photo in both cameras using camera2 api.
Any help will be highly motivated to me.

**Comment by Aish05** [comment]
Any solutions to this?
Facing the same issue

**Comment by Mokkakopf** [comment]
You may hace a look here: 
https://stackoverflow.com/a/33932778/2987847
There is a discussion going on in the comments to that solution

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
