### ISSUE TITLE
onCaptureProgressed and onCaptureCompleted being called infinitely

### ISSUE THREAD

**Issue by robbykim** [googlesamples/android-Camera2Basic#91]
I just started with the baseline code and added it to a pretty barebones fragment in my project. When I start it up, I'm getting the onCaptureProgressed and onCaptureCompleted callbacks in my `mCaptureCallback` being called infinitely. Has any run into this?

**Comment by MarekBatkowski** [comment]
How did you solve this? I have the same issue.
