### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by NirpE** [googlesamples/android-Camera2Basic#93]
Using:

`StrictMode.setVmPolicy(new StrictMode.VmPolicy.Builder().detectAll().penaltyLog().penaltyDeath().build());`

And creating blank activity which launches `CameraActivity` by tapping button and pressing back, tapping button -> repeat process there is memory leak.

> com.example.android.camera2basic E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks. java.lang.Throwable: Explicit termination method 'release' not called at dalvik.system.CloseGuard.open(CloseGuard.java:180) at android.view.Surface.setNativeObjectLocked(Surface.java:511) at android.view.Surface.(Surface.java:179) at com.example.android.camera2basic.Camera2BasicFragment.createCameraPreviewSession(Camera2BasicFragment.java:684) at com.example.android.camera2basic.Camera2BasicFragment.access$400(Camera2BasicFragment.java:74) at com.example.android.camera2basic.Camera2BasicFragment$2.onOpened(Camera2BasicFragment.java:194) at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java:134) at android.os.Handler.handleCallback(Handler.java:751) at android.os.Handler.dispatchMessage(Handler.java:95) at android.os.Looper.loop(Looper.java:154) at android.os.HandlerThread.run(HandlerThread.java:61) 11-12 12:52:19.506 16069-16078/com.example.android.camera2basic W/System.err: StrictMode VmPolicy violation with POLICY_DEATH; shutting down.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
