### ISSUE TITLE
CONTROL_EFFECT_MODE doesn't work with Huawei P10

### ISSUE THREAD

**Issue by LacazeJess** [googlesamples/android-Camera2Basic#96]
Hey everybody,

I trying to use Camera2 with my Huawei P10 and my compatibility is LIMITED with the API.
When I check the available effects I receive the following list : off(0), mono(1), negative(2) and sepia(4).
So I set the key-value CONTROL_EFFECT_MODE-CONTROL_EFFECT_MODE_NEGATIVE to my builder and my preview doesn't change...

The same code work with my Sony Xperia XA.

Are there an alternative to control the camera to set negative effect to my preview ?
Or any advice to resolve my problem ?

Thanks

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
