### ISSUE TITLE
Doesn't work on samsung galaxy S7 front camera

### ISSUE THREAD

**Issue by liaogz82** [googlesamples/android-Camera2Basic#99]
Hi I change the following code from 

```
if (facing != null && facing == CameraCharacteristics.LENS_FACING_FRONT) {
    continue;
}
```
to
```
if (facing != null && facing == CameraCharacteristics.LENS_FACING_BACK) {
    continue;
}
```
because I want to use the front camera for my app

But the camera is not working. Pressing the button does not result in anything being saved. What is the difference between using the front and the back camera?

**Comment by AntonioVitiello** [comment]
I have the same problem on my Samsung Galaxy Note 3, why?
Has anyone found a solution?

**Comment by HadirKB** [comment]
This new class android.hardware.camera2 didn't work with me too on Sumsung, I was obliged to use the deprecated class android.hardware.camera

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
